development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
